Order manager
DmitryIldyukov/TLPractice pull request #1
Opened 2024-06-28 06:37 UTC by DmitryIldyukov

2024-07-03 07:46 UTC, Nafanyan requested changes
Круто!

Хорош, попили всё на методы, выделил отдельный класс для хранения информации о заказе, но есть некоторые замечания)

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +public class Order
давай класс вытащим в отдельный файл)

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +    public Order( string productName,
давай в одну строчку, вроде как нормально умещается:
```c#
    public Order( string productName, int quantity, string customerName, string address )
```

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +    public string ProductName { get; private set; }
Обычно свойства пишутся выше конструктора)

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +            if ( string.IsNullOrWhiteSpace( input ) )
у if лучше указывать фигурные скобочки, даже если логика под условием небольшая)

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +                $"Ожидайте доставку по адресу {order.Address} к {DateTime.UtcNow.AddDays( 3 ).ToLocalTime().ToShortDateString()}" );
``` c#
{DateTime.UtcNow.AddDays( 3 ).ToLocalTime().ToShortDateString()}
```

не очень хорошо выполнять подобные преобразования, потому как передавая объект, которые содержит информацию, лучше чтобы он уже имел достоверные данные, которые  необходимо только вывести

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +        while ( !int.TryParse( Console.ReadLine(), out quantity ) || quantity <= 0 )
раз у тебя есть отдельная функция для валидации ввода строкового типа, то можно и написать функцию для валидации входных числовых данных, так будет смотреться лаконичнее)

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +    // Вынес в отдельный метод, т.к. в теории тут будет выполняться множество других методов
Комментарии, за исключением особенностей бизнес логики, избыточны, но спасибо я ценю твоё желание облегчить мне понимание твоего кода)

Только немного не понял "в теории тут будет выполняться множество других методов", где тут? каких методов?

2024-07-03 07:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +        while ( !int.TryParse( Console.ReadLine(), out quantity ) || quantity <= 0 )
ещё лучше ставить фигурные скобочки)

2024-07-03 18:48 UTC, DmitryIldyukov commented on OrderManager/Program.cs
> +    // Вынес в отдельный метод, т.к. в теории тут будет выполняться множество других методов
Решил добавить комментарий, т.к. подумал, что выносить в отдельный метод вывод в консоль одной строки не совсем правильное решение (т.к. этот метод используется лишь в одном месте) Тем не менее все же вынес, потому что, если продумывать логику доставки далее, то в этих методах будут еще другие методы, например, сборка заказа)

2024-07-04 05:46 UTC, Nafanyan approved these changes
Всё супер, только мелкие недочеты)

Прежде чем мержить сделай squash, это специальный механизм для объединения нескольких коммитов в один. Будет неприятно если у тебя в main попадет 6 коммитов исправлений по одной задаче, лучше пусть будет один)

Насколько я знаю в гитхабе это можно сделать выбрав
![image](https://github.com/DmitryIldyukov/TLPractice/assets/90004716/97b9cc29-6853-4e64-acca-7cd8af7d5608)

2024-07-04 05:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +    static Order CreateOrder()
Скорее придирка, давай размещать методы в порядке их вызова, чем раньше вызывается метод, тем  выше он будет стоять, так иерархия будет следующая:
CreateOrder()
GetNonEmptyStringFromConsole
GetValidProductQuantity
....
OrderCancelation

2024-07-04 05:46 UTC, Nafanyan commented on OrderManager/Program.cs
> +        return new Order( productName: productName, quantity: quantity, customerName: customerName, address: address );
именованные аргументы это иногда необходимо, но здесь как будто идет дублирование, давай уберем)

Имена переменных итак описывают входные данные, необходимые для создания объекта Order

2024-07-06 07:28 UTC, merged