Fighters
DmitryIldyukov/TLPractice pull request #3
Opened 2024-07-07 12:04 UTC by DmitryIldyukov

2024-07-21 06:48 UTC, Nafanyan commented
Сделал я таких персонажей)
<img width="267" alt="image" src="https://github.com/user-attachments/assets/7609a05b-6c15-4b76-8874-c70cab1c60ab">

И у меня возник вопрос как атакующий наносит 0 урона, а защищающийся получает 1. Я бы понял если бы было наоборот, нанёс 1, а прошло 0 из-за брони, но тут как будто как-то странно)
<img width="381" alt="image" src="https://github.com/user-attachments/assets/d3bf73cd-8530-4685-931c-edceab64328c">

2024-07-21 07:25 UTC, Nafanyan requested changes
В целом очень даже хорошо!

Только есть некоторые вопросики)

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/Models/Fighters/Fighter.cs
> +        int newHealth = CurrentHealth - ( Math.Max( opponentDamage - ArmorPoints, 1 ) );
если оппонент нанесет 0 урона, то боец получит 1 единицу урона, как так)

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/Models/Fighters/Fighter.cs
> +    public Fighter( string name,
```c#
    public Fighter(
        string name,
        IFighterType fighterType,
        IRace race,
        IWeapon weapon,
        IArmor armor )
```

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/Services/FighterService.cs
> +    private string GetNonEmptyStringFromConsole( string message,
``` c#
    private string GetNonEmptyStringFromConsole(
        string message,
        string errorMessage = "Неверный ввод. Введенная строка не может быть пустой. Попробуйте снова." )
```

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/GameMaster/GameManager.cs
> +        Console.WriteLine( message );
можно 
``` c#
Console.WriteLine( message + '\n');
```
а Console.WriteLine(); убрать)

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/GameMaster/GameManager.cs
> +        Console.WriteLine( message );
аналогично в других местах

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/GameMaster/GameManager.cs
> +        IFighter winner = null;
какой-то монолит кода, давай логические пустые строки поставим)

2024-07-21 07:25 UTC, Nafanyan commented on Gladiators/GameMaster/GameManager.cs
> +        Console.WriteLine( $"{fighter.Name} атакует {opponent.Name} и наносит ему {damage} урона." );
небольшая путанница с "наносит" и "получает", может сделать что-то вроде:
``` c#
        Console.WriteLine( $"{fighter.Name} атакует {opponent.Name} с силой равной {damage}." );
        if ( damageTaken < damage )
        {
            Console.WriteLine( $"{opponent.Name} частично блокирует атаку, получает {damageTaken} урона и {( opponent.IsAlive ? "выживает" : "погибает" )}." );
        }
        else
        {
            Console.WriteLine( $"{opponent.Name} получает {damageTaken} урона и {( opponent.IsAlive ? "выживает" : "погибает" )}." );
        }
```

???

2024-07-21 12:01 UTC, DmitryIldyukov commented on Gladiators/Models/Fighters/Fighter.cs
> +        int newHealth = CurrentHealth - ( Math.Max( opponentDamage - ArmorPoints, 1 ) );
Было сделано, чтобы не было бесконечного цикла при поединке, когда у бойцов очки брони больше, чем урон) 
Решил добавить состояние для брони

2024-07-21 12:02 UTC, DmitryIldyukov commented on Gladiators/GameMaster/GameManager.cs
> +        Console.WriteLine( $"{fighter.Name} атакует {opponent.Name} и наносит ему {damage} урона." );
Да, так более понятно)

2024-07-24 05:35 UTC, Nafanyan approved these changes
Всё круто, отлично может squash'шить и мержить)

2024-07-24 07:53 UTC, merged