Add sql
DmitryIldyukov/TLPractice pull request #5
Opened 2024-07-11 19:32 UTC by DmitryIldyukov

2024-07-16 19:38 UTC, Nafanyan requested changes
понимание есть, это видно, но как будто поторопился)

2024-07-16 19:38 UTC, Nafanyan commented on sql/SQLQuery.sql
> +CREATE TABLE dbo.rooms
такую миграцию повторно не запустишь, она не идемпотентна, лучше перед созданием проверять вдруг такая таблица уже существует через
```sql
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dbo.rooms')
```

2024-07-16 19:38 UTC, Nafanyan commented on sql/SQLQuery.sql
> +	r.room_id,
или можно r.* и уместить select и from на одной строчке

2024-07-16 19:38 UTC, Nafanyan commented on sql/SQLQuery.sql
> +SELECT *
лучше умещать select и from на одной строке)

2024-07-16 19:38 UTC, Nafanyan commented on sql/SQLQuery.sql
> +WHERE b.room_id = 1;
room_id это id внутри базы данных, за её пределами никто не знает о её существовании, тут речь идет об room_number таблицы rooms

2024-07-16 19:38 UTC, Nafanyan commented on sql/SQLQuery.sql
> +-- Поиск всех номеров, которые не забронированы на определенную дату.
Получил такой вывод, как будто забронированные номера тоже отобразились)
<img width="724" alt="image" src="https://github.com/user-attachments/assets/3f715182-5178-408b-ab5f-97bb940acc5f">

2024-07-21 06:22 UTC, Nafanyan requested changes
В остальном всё хорошо)

По комментам: мелочи по форматированию и интересный вопросик по последнему заданию))

2024-07-21 06:22 UTC, Nafanyan commented on sql/SQLQuery.sql
> +WHERE
Отступы лучше использовать для отображения вложенности, у тебя вложенности по моему никакой нет)

```sql
SELECT DISTINCT r.* FROM rooms as r
JOIN bookings as b on r.room_id = b.room_id
WHERE GETDATE() NOT BETWEEN b.check_in_date AND b.check_out_date AND r.availability = 1;
```

2024-07-21 06:22 UTC, Nafanyan commented on sql/SQLQuery.sql
> +	JOIN customers as c on b.customer_id = c.customer_id
читай комент о вложенности выше)

2024-07-21 06:22 UTC, Nafanyan commented on sql/SQLQuery.sql
> +	WHERE '11.07.2024' BETWEEN b.check_in_date AND b.check_out_date
уверен что у тебя дата в таком формате хранится?)) '11.07.2024'

2024-07-21 07:53 UTC, DmitryIldyukov commented on sql/SQLQuery.sql
> +	WHERE '11.07.2024' BETWEEN b.check_in_date AND b.check_out_date
Надеюсь, я правильно понял) 
Дата в виде дд.мм.гггг тоже подходила и запрос выполнялся корректно, но для лучшей читабельности перевел в вид гггг-мм-дд

2024-07-22 13:43 UTC, Nafanyan approved these changes

2024-07-22 13:43 UTC, Nafanyan commented on sql/SQLQuery.sql
> +	WHERE '11.07.2024' BETWEEN b.check_in_date AND b.check_out_date
хм, да, ты прав, видимо я с запросом как-то косячнул у себя, сорян))

2024-07-22 14:56 UTC, merged