Add Theater
DmitryIldyukov/TLPractice pull request #7
Opened 2024-08-01 04:49 UTC by DmitryIldyukov

2024-08-01 05:54 UTC, Nafanyan requested changes

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Domain/Entities/WorkingHours.cs
> +public class WorkingHours
а может Theater hours?

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Domain/Entities/WorkingHours.cs
> +    public int TheaterId { get; set; }
тебе точно здесь нужен TheaterId ? ты же его можешь получить через Theater, или я чего-то не понимаю?)

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Infrastructure/Data/Migrations/20240730191732_InitialMigration.cs
миграции лучше выносить в отдельный проект Infrastructure.Migrations)

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Infrastructure/Configuration/DependencyInjection.cs
может назовем класс Bindings?

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Application/Interfaces/Repositories/ICompositionRepository.cs
> +    Task<IEnumerable<Composition>> GetAll();
GetAll() очень дорогая операция и в дальнейшем может нехило так усложнить жизнь твоей БД, давай выставим примерные параметры по которым будем делать выгрузку)

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Application/Interfaces/Repositories/IWorkingHoursRepository.cs
> +    Task CreateWorkingHours( WorkingHours workingHours );
в других интерфейсах подобная команда называется Create, а здесь CreateWorkingHours, нужно единообразие. аналогично с другими командами)

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Application/UseCases/Commands/Author/Create/CreateAuthorCommandHandler.cs
> +        if ( string.IsNullOrEmpty( command.Name ) )
Валидацию можно вынести в отдельный метод)
Аналогично с другими UseCase'ами

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Application/UseCases/Commands/Author/Delete/DeleteAuthorCommandHandler.cs
> +        await _authorRepository.Delete( command.AuthorId );
а что я получу если захочу удалить автора с id 666, когда их в системе всего 10? :)

2024-08-01 05:54 UTC, Nafanyan commented on Spotlight/Application/Common/CQRS/Command/ICommandHandler.cs
> +﻿using MediatR;
интересная либа, я прочитаю про неё и вернусь с вопросами)

2024-08-05 18:09 UTC, DmitryIldyukov commented on Spotlight/Domain/Entities/WorkingHours.cs
> +    public int TheaterId { get; set; }
Думаю, что нужен, использую как внешний ключ, но судя по всему можно и как то по другому связывать сущности, но я не знаю как)

2024-08-05 18:11 UTC, DmitryIldyukov commented on Spotlight/Application/Interfaces/Repositories/ICompositionRepository.cs
> +    Task<IEnumerable<Composition>> GetAll();
Заменил GetAll только у репозиториев композиций и представлений (Composition и Play), думаю у других только через пагинацию получится упростить запрос

2024-08-05 18:14 UTC, DmitryIldyukov commented on Spotlight/Application/UseCases/Commands/Author/Delete/DeleteAuthorCommandHandler.cs
> +        await _authorRepository.Delete( command.AuthorId );
На лекции Данил поднимал вопрос о том, что лучше возвращать при удалении по id, вроде как пришли к мнению, что нужно возвращать всегда 200Ok или 204NoContent т.к. иначе можно путем перебора найти id
Только поэтому решил возвращать при любом исходе 204NoContent)

2024-08-09 05:51 UTC, Nafanyan approved these changes
Ты мега крут, без вопросов, красавчик

2024-08-11 14:03 UTC, merged